### PR TITLE
Edited our first paragraph and fixed spacing.

### PR DESCRIPTION
**Pull request by Karla-Isabel-Sandoval**
Changed syntax errors

### CODE REVIEW

**Comment by orta** [comment]
want to close this PR and re-create one that goes to the CP blog instead of your fork?

**Comment by Karla-Isabel-Sandoval** [comment]
@orta, Yes. I can close it. Thanks for asking :)

**Comment by Karla-Isabel-Sandoval** [comment]
@orta would this 'https://github.com/CocoaGems/blog.cocoapods.org', be the correct place to make the PR?

**Comment by orta** [comment]
It needs to go from `https://github.com/CocoaGems/blog.cocoapods.org` to `'https://github.com/CocoaPods/blog.cocoapods.org` in order for it to update our blog :+1:

**Comment by orta** [comment]
Hitting the PR button on https://github.com/CocoaGems/blog.cocoapods.org should offer the chance to send it to `CocoaPods`

**Comment by Karla-Isabel-Sandoval** [comment]
Hi @orta Thanks for offering the proper link for making a PR to CocoaPodsBlog.
In the comparing changes page there are several options to choose from. Which selection across all 4 comparisons would allow me to PR my changes with the CP Blog?
screenshot 2016-02-08 11 01 12
screenshot 2016-02-08 10 57 56
screenshot 2016-02-08 10 57 56
screenshot 2016-02-08 11 01 12
screenshot 2016-02-08 11 01 35
screenshot 2016-02-08 11 01 49
screenshot 2016-02-08 11 01 58
screenshot 2016-02-08 11 02 07

**Comment by orta** [comment]
the base is cocoagems, the receiving is cocoapods

**Comment by Karla-Isabel-Sandoval** [comment]
@orta When I select Cocoagems/blog.cocoapods.org as a base fork using the link you provided, the default head fork comparison becomes master, and the message I receive is https://www.dropbox.com/s/c6zqwqet6q0rzil/Screenshot%202016-02-08%2014.51.58.png?dl=0 This seems off to me because the message says, 'There isn't anything to compare'.

**Comment by orta** [comment]
You want to send code from:

`Cocoagems/blog.cocoapods.org` on the branch `RevisionsForRGSoCBlogPost` to
`cocoapods/blog.cocoapods.org` to the branch `master`

**Pull request closed without merging**
